name: Check if the PR branch is rebased

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check if the branch is rebased
      run: |
        git remote set-branches --add origin master
        git fetch
        hash1=$(git show-ref --heads -s origin/master)
        hash2=$(git merge-base origin/master HEAD)
        echo $hash1
        echo $hash2
        [ "${hash1}" = "${hash2}" ] && exit 0 || exit 1
